// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJN5_BQX188TN5a73whZM-6eVOa3seevU',
    appId: '1:461184863931:web:056c84cd8d0f7faef8639e',
    messagingSenderId: '461184863931',
    projectId: 'help-student-f79b9',
    authDomain: 'help-student-f79b9.firebaseapp.com',
    storageBucket: 'help-student-f79b9.appspot.com',
    measurementId: 'G-YWQ8DFSG3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeX1XR5TD6sMa24z2IT1JAV-9h1QxmkWE',
    appId: '1:461184863931:android:286a16d2990cf9a4f8639e',
    messagingSenderId: '461184863931',
    projectId: 'help-student-f79b9',
    storageBucket: 'help-student-f79b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmftCcO--BadKd31BWdYRYQBLxVG-OYFI',
    appId: '1:461184863931:ios:7cfedb86bd333f2df8639e',
    messagingSenderId: '461184863931',
    projectId: 'help-student-f79b9',
    storageBucket: 'help-student-f79b9.appspot.com',
    iosClientId: '461184863931-8lge2gis4bf8lc6o0i7cq3u6fhan28mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmftCcO--BadKd31BWdYRYQBLxVG-OYFI',
    appId: '1:461184863931:ios:7cfedb86bd333f2df8639e',
    messagingSenderId: '461184863931',
    projectId: 'help-student-f79b9',
    storageBucket: 'help-student-f79b9.appspot.com',
    iosClientId: '461184863931-8lge2gis4bf8lc6o0i7cq3u6fhan28mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpStudent',
  );
}
